stages:
  - test
image: docker:stable

test:
  stage: test
  image: python:3.7-alpine3.9
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - apk add python
  - python -v
  - python __main__.py tests/test-level-1.json
  - python __main__.py tests/test-level-2.json
  - python __main__.py tests/test-level-3.json
  - python __main__.py tests/test-level-4.json