stages:
  - test

test:
  stage: test
  image: python:3.6
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
  - python3 -v
  - python3 run_tests.py